version: '3'

services:
  app:
    build: .
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: ${URL}
      VIRTUAL_PORT: ${NODE_PORT}
    expose:
      - ${NODE_PORT}
    volumes:
      - geo-communes-api-sources:/api/sources
    env_file: .env

volumes:
  geo-communes-api-sources:
    external: true

networks:
  default:
    external:
      name: nginx-proxy
