version: '3'

services:
  communes-api:
    build: .
    environment:
      VIRTUAL_HOST: ${URL}
      VIRTUAL_PORT: ${NODE_PORT}
      LETSENCRYPT_HOST: ${URL}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    expose:
      - ${NODE_PORT}
    volumes:
      - geo-communes-api-sources:/app/sources
      - ./.env:/app/.env
    restart: always

volumes:
  geo-communes-api-sources:
    external: true

networks:
  default:
    external:
      name: nginx-proxy
